# Generated by Django 6.0.1 on 2026-02-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0003_alter_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('order', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linesegments', to='selector.document')),
            ],
        ),
    ]
