# Generated by Django 6.0.1 on 2026-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0004_linesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesegment',
            name='transcribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linesegment',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='linesegment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
