# Generated by Django 6.0.1 on 2026-02-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0005_linesegment_transcribed_linesegment_transcription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linesegment',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
