# Generated by Django 6.0.1 on 2026-02-16 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0007_alter_document_options_alter_linesegment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linesegment',
            name='last_transcribed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcribed_segments', to=settings.AUTH_USER_MODEL, verbose_name='آخرین رونوشت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='linesegment',
            name='last_verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_segments', to=settings.AUTH_USER_MODEL, verbose_name='آخرین بازبین'),
        ),
    ]
