# Generated by Django 6.0.1 on 2026-02-16 09:24

from django.db import migrations, models
import re


def populate_notebooks_and_pages(apps, schema_editor):
    Document = apps.get_model("selector", "Document")
    Notebook = apps.get_model("selector", "Notebook")

    for doc in Document.objects.all():
        notebook_name = doc.name
        page_number = None

        # Parse name: expect x_y_z_pNum, extract x_y_z and pNum
        if doc.name and "_" in doc.name:
            parts = doc.name.rsplit("_", 1)
            if len(parts) == 2:
                notebook_name, pnum = parts
                page_match = re.search(r"p(\\d+)$", pnum)
                if page_match:
                    page_number = int(page_match.group(1))

        # Create or get Notebook
        notebook_obj, _ = Notebook.objects.get_or_create(name=notebook_name)
        doc.notebook = notebook_obj
        if page_number is not None:
            doc.page = page_number
        doc.save(update_fields=["notebook", "page"])


class Migration(migrations.Migration):
    dependencies = [
        ("selector", "0009_notebook_linesegment_page_document_notebook"),
    ]

    operations = [
        migrations.RunPython(populate_notebooks_and_pages),
    ]
