# Generated by Django 6.0.1 on 2026-02-15 06:26

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    MyModel = apps.get_model("selector", "LineSegment")

    for obj in MyModel.objects.all():
        if obj.verified is True:
            obj.verification = 1
        elif obj.verified is False:
            obj.verification = 2
        obj.save(update_fields=["verification"])


def reverse_func(apps, schema_editor):
    MyModel = apps.get_model("selector", "LineSegment")

    for obj in MyModel.objects.all():
        if obj.verification == 1:
            obj.verified = True
        else:
            obj.verified = False
        obj.save(update_fields=["verified"])


class Migration(migrations.Migration):
    dependencies = [
        ("selector", "0006_alter_linesegment_transcription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "سند", "verbose_name_plural": "اسناد"},
        ),
        migrations.AlterModelOptions(
            name="linesegment",
            options={
                "verbose_name": "تکه خط",
                "verbose_name_plural": "تکه\u200cهای خط",
            },
        ),
        migrations.AddField(
            model_name="linesegment",
            name="verification",
            field=models.SmallIntegerField(
                choices=[(0, "بررسی نشده"), (1, "قبول"), (2, "رد")],
                default=0,
                verbose_name="تایید شده",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to="", verbose_name="فایل"),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(blank=True, max_length=250, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="linesegment",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linesegments",
                to="selector.document",
                verbose_name="سند",
            ),
        ),
        migrations.AlterField(
            model_name="linesegment",
            name="file",
            field=models.FileField(upload_to="", verbose_name="فایل"),
        ),
        migrations.AlterField(
            model_name="linesegment",
            name="order",
            field=models.IntegerField(verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="linesegment",
            name="transcribed",
            field=models.BooleanField(default=False, verbose_name="رونوشت شده"),
        ),
        migrations.AlterField(
            model_name="linesegment",
            name="transcription",
            field=models.TextField(blank=True, verbose_name="رونوشت"),
        ),
        migrations.AlterField(
            model_name="linesegment",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="تایید شده"),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(model_name="linesegment", name="verified"),
    ]
