# Generated by Django 6.0.1 on 2026-02-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0008_linesegment_last_transcribed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'جزوه',
                'verbose_name_plural': 'جزوات',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.IntegerField(null=True, verbose_name='شماره صفحه'),
        ),
        migrations.AddField(
            model_name='document',
            name='notebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='selector.notebook'),
        ),
    ]
