# Generated by Django 6.0.1 on 2026-02-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0010_populate_notebooks_and_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
